variable "prefix" {}
variable "region" {}
variable "hub_vnet_address_space" {}
variable "hub_subnets" {}
variable "tags" {}
variable "domain_fqdn" {}
variable "spoke_vnet_address_space" {}
variable "spoke_subnets" {}
variable "digicert_key_vault" {}
variable "digicert_resource_group_name" {}
variable "name_string_suffix" {}
variable "validation_key" {}
variable "decryption_key" {}
variable "rds_license_mode" {}

#variable "webaccess_fqdn" {}
#variable "session_host_fqdns" {}
#variable "broker_group_name" {}
#variable "session_group_name" {}
#variable "gateway_group_name" {}
#variable "web_group_name" {}
#variable "broker_hosts" {}
#variable "session_hosts" {}
#variable "gateway_hosts" {}
#variable "web_hosts" {}
#variable "broker_record_name" {}
#variable "gateway_record_name" {}
#variable "web_record_name" {}
#variable "collection_name" {}
#variable "collection_description" {}
