variable "aduser_password" {}
variable "active_directory_netbios_name" {}
variable "broker_group_name" {}
variable "session_group_name" {}
variable "gmsa_account_name" {}
variable "active_directory_domain" {}
variable "broker_record_name" {}
variable "broker_ip" {}
variable "sqladmin_password" {}
variable "vm_name" {}
variable "rg_name" {}
variable "sql_vm_name" {}
variable "broker_vm_name" {}
variable "session_vm_name" {}
variable "gateway_vm_name" {}